### ISSUE TITLE
GitHub ignores directories called `examples`

### ISSUE THREAD

**Issue by lpil** [mad4j/book-mdpc#19]
Hello!

Github ignores directories called `examples` so this repo shows up as shell rather than Processing. I think it'd be good if this directory was renamed so that GitHub lists it as Processing, so that people looking for art projects can find this one easier :)

Cheers,
Louis

**Comment by mad4j** [comment]
Thanks!
Processing needs that collections of examples are bundled in a specific structure.
Preferred to change default GitHub preferences by adding Linguist params to `.gitattribute` configuration file.
Now the project is **100% Processing**!!

Thanks,
Daniele

**Comment by lpil** [comment]
I didn't know that trick, nice one :)
